// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC--dG7hebrMKNCvKJFyIGgxMvP6FY8d8',
    appId: '1:388638913870:web:e489ed8039663bb66bda1f',
    messagingSenderId: '388638913870',
    projectId: 'tvcare-c9891',
    authDomain: 'tvcare-c9891.firebaseapp.com',
    storageBucket: 'tvcare-c9891.firebasestorage.app',
    measurementId: 'G-XLCLRX9WC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO16wI9Vw-wsEpRYEPluOZ4XHi7RVQyX4',
    appId: '1:388638913870:android:f1f4daf29980ebdc6bda1f',
    messagingSenderId: '388638913870',
    projectId: 'tvcare-c9891',
    storageBucket: 'tvcare-c9891.firebasestorage.app',
  );
}
